// <auto-generated />
namespace SMS_R33.API.Migration.Token
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DbCreateUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbCreateUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201602022_DbCreateUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
